language: python

python:
  - 3.7

sudo: false

install:
  - pip install tox
  - pip install python-coveralls

script: tox

after_success:
  - coveralls

cache:
  directories:
    - $HOME/.cache/pip
    - .tox
